### ISSUE TITLE
Problem converting mutiple PAR files in a folder

### ISSUE THREAD

**Issue by julienbesle** [xiangruili/dicm2nii#2]
When converting multiple files or a full folder, for instance by typing
`dicm2nii('*.PAR','.')`
not all files get converted (sometimes because the file causes an error, but not always), and  no error/warning message is printed out. 

If the same files are converted individually and result in an error, then I get the matlab error, for instance:
```
Validating 1 files ...
 No valid files found:

Index exceeds matrix dimensions.
.
```

On the other hand, some files get converted when dicm2nii is called only for this file, but not when it is called for all PAR files in the folder

You can try this in the Dropbox folder. If you add a file that is converted without error at the end of the folder (for instance by calling them xxx.REC and xxx.PAR), you will see that only 6 files get converted, when there are 10 files in the folder, and only 2 that give an error when converted individually

**Comment by xiangruili** [comment]
This is due to the limited ability to deal with different errors. With current version, this behavior is expected: if there is no valid series, the converter will show error message; if there is 1+ series convertible, some failed series may not be reported. 

This should be improved so that it won't show error like "not a dicom file", while it does show error if a dicom or other convertible file fails to convert.

Let's leave this issue open until I improve the error dealing in the future. Thanks.

**Comment by julienbesle** [comment]
It's not just files that cause an error or are not valid. There are cases
where files that can be converted individually are somehow skipped when
converting multiple files.

Also, i think it would be important to issue a warning fir any file that
does not get converted, even if the cause is unknown

Julien

**Comment by xiangruili** [comment]
@julienbesle That is a serious problem. I think the reason is that two PAR files may have the same SeriesNumber, and they can't be converted into one NIfTI. The last commit hopefully fixes this by making up SeriesInstanceUID using both file name and SeriesNumber.
It would be great if you can confirm the fix. Thanks.
