### ISSUE TITLE
Phillips Multi-Echo Multiband fMRI data

### ISSUE THREAD

**Issue by tombresser** [xiangruili/dicm2nii#26]
Hi,

We have just started to use your tool to convert PAR/REC files into nifti's after recommendation by FSL. We are pretty happy with the results. Only our Multi-echo multiband fmri sequence is not converted.

> Inconsistent image size, bits etc: /path/multi_echo_multi_band.PAR

Is it possible to convert this file? 
When using dcm2niix it converts it into three seperate nifti's (one for each echo), maybe this is also a possibility in this toolbox? 
We appreciate the dcmHeader.mat that your toolbox saves.

Kind regards,
Tom Bresser

**Comment by neurolabusc** [comment]
@xiangruili sample datasets are courtesy of Baxter Rogers are [available](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Unusual_MRI). Where possible, I would strongly encourage Philips users to export data to DICOM rather than PAR/REC. PAR/REC is a proprietary vendor format, and while it is human readable its usage has changed over the years. Further, there are documented bugs that some Philips products created, and while dicm2nii and dcm2niix both attempt to detect these (and we think Philips has updated their tools), it is possible there are corner cases that the community is not aware of. Both @xiangruili and I work at sites where we do not have access to Philips hardware. While we have both devoted time to supporting these images, our limited exposure to them means that it is possible they have attributes we are not aware of.

**Comment by zashams** [comment]
> @xiangruili sample datasets are courtesy of Baxter Rogers are [available](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Unusual_MRI). Where possible, I would strongly encourage Philips users to export data to DICOM rather than PAR/REC. PAR/REC is a proprietary vendor format, and while it is human readable its usage has changed over the years. Further, there are documented bugs that some Philips products created, and while dicm2nii and dcm2niix both attempt to detect these (and we think Philips has updated their tools), it is possible there are corner cases that the community is not aware of. Both @xiangruili and I work at sites where we do not have access to Philips hardware. While we have both devoted time to supporting these images, our limited exposure to them means that it is possible they have attributes we are not aware of.

Hi,

I've started using your tool for converting Philips PAR/REC of multi-echo GRE data to NIFTI and I just came across to this issue page. You suggested using DICOM images rather than the parrec files. However, all the echoes from the ME-GRE data, which I need them separately, are already combined in the DICOMs. So I could only use the PAR/REC files in order to get all the information from all the echoes. Do you think I can still use your tool without adapting anything in the code for parrect to nifti conversion?

**Comment by xiangruili** [comment]
@zashams 
Did you mean the dicom output combines multi-echo into a single dataset?
You will need to try if nifti from the par/rec works fine. As @neurolabusc pointed out, par file is human readable (good), but it is easy to introduce problem, especially when a new parameter is added. 
I suppose dicm2nii.m will save nifti for multi echoes, but I am not sure the the format is what you prefer.
Let us know if how it goes.
