### ISSUE TITLE
Philipps parrec conversion to nifti failed: Product of known dimensions, 98, not divisible into total number of elements, 3621

### ISSUE THREAD

**Issue by JosZimmermann** [xiangruili/dicm2nii#39]
Hi,

Previously, I converted successfully T1 and DTI parrec files from our Philipps Scanner using your dicm2nii function. However, since a standard release update on the Philipps Scanner (version 5.4.1 to 5.6.1) I get the error message printed below (for T1 and DTI). However, I know that this data is valid as it has been used in an other study. Any idea what could be the issue?

Best wishes,
Josua

Validating 2 files ... (0 valid)
 No valid files found:
Product of known dimensions, 98, not divisible into total number of elements, 3621.
Unknown file type: D:\DTI\Data\BIDS\sub-117\dwi\sub-117_dwi.REC.

Validating 2 files ... (0 valid)
 No valid files found:
Size arguments must be real integers.
Unknown file type: D:\DTI\Data\BIDS\sub-117\anat\sub-117_T1w.REC.

**Comment by xiangruili** [comment]
The likely reason is that the converter fails to read PAR file correctly. Do you mind to share one of the PAR files which gives the error?

**Comment by JosZimmermann** [comment]
Thank you for your reply. I have sent you and Chris (he asked me via mail) a test dataset. You should have received a link by mail.

**Comment by xiangruili** [comment]
@JosZimmermann Thank you for sharing the dataset.
It turns out that Philips tries to output some new parameters in the table, and totally messed up the parsing. They try to add 7 new parameters, as noted in the "IMAGE INFORMATION DEFINITION", but add only three of them to the table. 
Even worse, they don't bother to update the version number after introducing new parameters. 
My current solution is to not rely on the row definition, but assume the later rows are problematic, and use only those rows we need in earlier versions. This will definitely fail if they decide to add or remove one or more of the earlier rows.
My suggestion is to use dicom when possible. The PAR text file is really fragile, and Philips often introduces errors into it.

**Comment by JosZimmermann** [comment]
Thank you for your support. Unfortunately, for this study we only have parrec files. But in future I will definitly use DICOMs as parrec seem to be prone to error.

**Comment by neurolabusc** [comment]
@drmclem may have some insights on this topic. It has been [reported](https://github.com/rordenlab/dcm2niix/issues/461) that `enhanced DICOM export on Philips scanner does not work well when having too many total slices`. Therefore, users may be forced to use PAR/REC for some circumstances. Beyond these edge cases, I think users be [aware of the limitations of PAR/REC](https://github.com/rordenlab/dcm2niix/issues/255) and avoid using it when possible. I agree with @xiangruili  that these sample images are not internally consistent between IMAGE INFORMATION DEFINITION and the IMAGE INFORMATION, and it is frustrating that the version number has not changed to aid detection and kludges. You may want to see if Philips can provide a service pack to rectify these issues.
