### ISSUE TITLE
Multiband acceleration factor

### ISSUE THREAD

**Issue by ArtemyVinogradov** [xiangruili/dicm2nii#60]
Hello,

I am currently trying to use dicm2nii in order to obtain header file information and one of the pieces I'm looking for is the multiband acceleration factor. 

Based on my understanding, I had thought that it was located in the CSA Series Header Info under "sSliceAcceleration.lMultiBandFactor". While this has worked for me recently, it suddenly gave me a "1" where the SMS factor was clearly "2" based on the timings. dcm2niix shows an multiband factor of 2 as well, so would you happen to know why it is giving me a "1" here?

Is there somewhere else that I may not be looking? Thank you so much for the help.

**Comment by xiangruili** [comment]
That is a known issue for some software versions, at least to Syngo VE11E. 
The ImageComments may have something like 'Unaliased MB3/PE3', but that can be easily overwritten if users selects to store any comments.
A better way may be to use s.CSAImageHeaderInfo.MosaicRefAcqTimes to detect the MB factor. But note that you should avoid using the first instance, since MosaicRefAcqTimes can be wrong in some versions.

**Comment by ArtemyVinogradov** [comment]
I see. Where could I find "ImageComments"? 

Funny you should mention that, as we are also extracting the slice timings using that exact parameter as well. I'm concerned now that we may be using the wrong times however, considering what you said. When you say "first instance", do you mean the one located outside of the s.CSAImageHeaderInfo? 

Thank you for the information. I greatly appreciate it!

**Comment by xiangruili** [comment]
ImageComments is a public dicom tag, but it is not reliable anyway.
first instance refers to the first volume dicom. One should avoid extracting timing from that one.
dicm2nii.m extracts SliceTiming and stored in multiple places, like dcmHeaders.mat, the text NIfTI extension, and json file if you choose so. You won't bother to extract yourself, since it is very error-prone in case of the flipped slices.

**Comment by neurolabusc** [comment]
@ArtemyVinogradov as @xiangruili notes, the `MosaicRefAcqTimes` for the first volume in a 4D multi-band volume may not be correct, so just read the CSA header from any other volume in the series. This issue was [described for the CMRR sequences](https://github.com/CMRR-C2P/MB/issues/29) but I think it also occurs for product sequences. Since is has been known since 2014, I think it exists in all pre-XA multi-band sequences (VB17-VE11).

**Comment by ArtemyVinogradov** [comment]
Understood! Thank you both for the explanation. I will keep this in mind moving forward!
