### ISSUE TITLE
Dimension error with PAR/REC file

### ISSUE THREAD

**Issue by joebathelt** [xiangruili/dicm2nii#65]
First of all, thank you for creating this fantastic conversion tool!

I'm encountering a problem with some of my PAR/REC files. When trying to convert them, I get the error `Product of known dimensions, 60, not divisible into total number of elements, 30312.`  when using dicm2nii with the default settings.

There were no errors during the data acquisition or when we exported the scans. I'd be extremely grateful for any advice on what might be causing the error and how to resolve it.

**Comment by xiangruili** [comment]
PAR file can be fragile in term of its format. If you don't mind, can you send me (xiangrui.li at gmail.com) the PAR file? REC file (the large one) is likely not needed for debug, but if you let me know the size of the REC file, that would be great.

**Comment by neurolabusc** [comment]
@joebathelt can you also send a [copy to my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by xiangruili** [comment]
The cause is the incomplete last volume. dicm2nii.m should take care of this, but in this case, there are two incomplete volumes, one for MAG and another for PHASE, so dicm2nii.m fails to deal with it. 
The version after 2024.04.05 should take care of this, but who knows what kind of weird thing Philips may implement.

**Comment by joebathelt** [comment]
Thank you very much. The update resolved the issue.
